apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-pod
          imagePullPolicy: IfNotPresent # dont forget to change later 
          image: wildsonbbl/gnnepcsaft:v2
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: django_secret_key
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: django_secret_key
            - name: domain_name
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: domain_name
            - name: django_allowed_hosts
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: django_allowed_hosts
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-in-svc
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  labels:
    name: webapp-ingress
spec:
  defaultBackend:
          service:
            name: webapp-in-svc
            port: 
              number: 8000


    
