apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-pod
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
        - name: webapp-container
          imagePullPolicy: IfNotPresent # dont forget to change later
          image: wildsonbbl/gnnepcsaft:v2
          resources:
            limits:
              memory: "2Gi"
              cpu: "2.0"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: DJANGO_ALLOWED_HOSTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: DB_PASSWORD
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DOMAIN_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DB_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: webapp-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  labels:
    name: webapp-ingress
spec:
  tls: 
  - hosts: 
    - gnnepcsaft.online
    secretName: webapp-secret-tls
  rules:
    - host: gnnepcsaft.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webapp-svc
                port:
                  number: 8000
