# Generated by Django 4.2.7 on 2023-12-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GnnepcsaftDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchi', models.CharField(max_length=255)),
                ('m', models.FloatField()),
                ('sigma', models.FloatField()),
                ('e', models.FloatField()),
                ('counting', models.IntegerField()),
            ],
        ),
    ]
