# Generated by Django 4.2.11 on 2024-10-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GnnepcsaftPara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inchi", models.CharField(max_length=255)),
                ("m", models.FloatField()),
                ("sigma", models.FloatField()),
                ("e", models.FloatField()),
                ("plot_den", models.CharField(max_length=50)),
                ("plot_vp", models.CharField(max_length=50)),
                ("plot_mol", models.CharField(max_length=50)),
            ],
        ),
    ]
