# Generated by Django 4.2.18 on 2025-02-02 23:21

from django.db import migrations, models

from ..utils import thermo_update_database


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThermoMLDenData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inchi", models.CharField(max_length=255)),
                ("den", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ThermoMLVPData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inchi", models.CharField(max_length=255)),
                ("vp", models.JSONField()),
            ],
        ),
        migrations.RunPython(thermo_update_database),
    ]
