# Generated by Django 4.2.7 on 2023-12-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GnnepcsaftDB',
            new_name='GnnepcsaftPara',
        ),
    ]
