# Generated by Django 4.2.18 on 2025-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnnepcsaftpara',
            name='e_ab',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gnnepcsaftpara',
            name='k_ab',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gnnepcsaftpara',
            name='mu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gnnepcsaftpara',
            name='na',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gnnepcsaftpara',
            name='nb',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
