# Generated by Django 4.2.27 on 2026-01-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GnnepcsaftPara',
        ),
    ]
