# Generated by Django 4.2.20 on 2025-04-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0002_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', max_length=100),
        ),
    ]
