# Generated by Django 4.2.20 on 2025-04-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0003_chatsession_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='selected_tools',
            field=models.JSONField(default=list),
        ),
    ]
