# Generated by Django 4.2.20 on 2025-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0004_chatsession_selected_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='selected_mcp_servers',
            field=models.JSONField(default=list),
        ),
    ]
