# Generated by Django 4.2.23 on 2025-08-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnnmodel', '0005_chatsession_selected_mcp_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
    ]
