services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/certs
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 50MB
    memswap_limit: 1G
    # networks:
    #   - ip6net1
    command:
      - --api.insecure
      - --accesslog
      - --providers.docker
      - --providers.docker.exposedbydefault=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      # - --entryPoints.web.http.redirections.entrypoint.to=websecure
      # - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=wil_bbl@hotmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --log.level=error

  webapp:
    scale: 1
    image: wildsonbbl/gnnepcsaft:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp-route.rule=HostRegexp(`gnnepcsaft.wildsonbbl.com`)"
      - "traefik.http.routers.webapp-route.entrypoints=web"
      - "traefik.http.routers.webapp-route.service=webapp-svc"
      - "traefik.http.services.webapp-svc.loadbalancer.server.port=8000"
      # - "traefik.http.routers.webapp-route.tls=true"
      # - "traefik.http.routers.webapp-route.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.webapp-route.tls.domains[0].main=gnnepcsaft.wildsonbbl.com"
      # - "traefik.http.routers.webapp-route.tls.domains[0].sans=gnnepcsaft.wildsonbbl.com"

    env_file:
      - .traefik-env
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: "1.0"
        reservations:
          memory: 350m
    memswap_limit: 1G
    command: ["bash", "-c", "daphne -b 0.0.0.0 -p 8000 webapp.asgi:application"]
#     networks:
#       - ip6net1

# networks:
#   ip6net1:
#     name: "ip6net1"
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#         - subnet: "fdf6:e94a:ba2d::/64"
#- gateway: "fdf6:e94a:ba2d::1"
#  docker network create --ipv6 --subnet="fdf6:e94a:ba2d::/64" --gateway="fdf6:e94a:ba2d::1" ip6net1
