entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  insecure: true

providers:
  docker:
    exposedByDefault: true
  #file:
  #  filename: /etc/traefik/tls.yaml

log:
  level: error

certificatesResolvers:
  letsencrypt:
    acme:
      email: wil_bbl@hotmail.com
      storage: /etc/certs/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
