entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  insecure: true

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/tls.yaml

log:
  level: debug
accessLog: {}

