name: Deploy to Azure VM 2

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to AZURE VM
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_AZURE }}
          HOSTNAME: ${{ secrets.AZURE_HOST2 }}
          USER_NAME: ${{ secrets.USER }}
          image: wildsonbbl/gnnepcsaft:v2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} <<'ENDSSH'
          sudo docker pull wildsonbbl/gnnepcsaft:v2
          sudo docker images
          ls
          sudo rm -rf .env
          sudo echo "${{ secrets.WEBAPP_ENV }}" > .env
          sudo docker compose up -d
          sudo docker image prune -f
          ENDSSH
