name: Deploy to GCP VM

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_GCP }}
          command_timeout: 30m
          script: |
            sudo docker compose down
            sudo docker pull wildsonbbl/gnnepcsaft:v2
            sudo docker images
            ls
            sudo rm -rf .env
            sudo echo "${{ secrets.WEBAPP_ENV }}" > .env
            sudo docker compose up -d
            sudo docker image prune -f

# curl --header "X-Forwarded-For: ${{ secrets.GCP_HOST }}" https://gnnepcsaft.online
