name: Deploy to GCP VM

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GCP VM
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_GCP }}
          HOSTNAME: ${{ secrets.GCP_HOST }}
          USER_NAME: ${{ secrets.USER }}
          image: wildsonbbl/gnnepcsaft:v2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} <<'ENDSSH'
          sudo docker pull wildsonbbl/gnnepcsaft:v2
          sudo docker images
          ls
          sudo docker compose up -d
          sudo docker image prune -f
          ENDSSH
