name: Deploy to Cloud Run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_KEY2 }}
      - id: "Deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "gnnepcsaftwebapp"
          image: "docker.io/wildsonbbl/gnnepcsaft:v2"
      - name: "Use output"
        run: 'curl "${{ steps.Deploy.outputs.url }}"'
