name: Pylint check up

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "**.py"

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv pip install pylint pylint-django pyinstaller tqdm
          uv pip install -r requirements.txt
          uv pip install -r requirements-llm.txt
          echo "${{ secrets.DESKTOP_ENV }}" > .env
      - name: Download models from HuggingFace
        run: |
          git clone https://huggingface.co/wildsonbbl/gnnepcsaft  hfdata
          cp hfdata/*.onnx* ./gnnmodel/static
          mkdir ./gnnmodel/productionfiles
          cp hfdata/*.onnx* ./gnnmodel/productionfiles
          python manage.py collectstatic --no-input
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --load-plugins pylint_django \
          --django-settings-module=webapp.settings --rcfile=.pylintrc
