name: Pylint

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv pip install --system pylint pylint-django pyinstaller tqdm
          uv pip install --system -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --load-plugins pylint_django \
          --django-settings-module=webapp.settings --rcfile=.pylintrc
